DimPlot(SQ_TFs, group.by = 'clusters', label = TRUE)
DimPlot(Om_TFs, group.by = 'clusters', label = TRUE)

##Put active ident cluster names as labels
Idents(object = Om_TFs) <- "clusters"
Idents(object = SQ_TFs) <- "clusters"


##Extract cells of interest into new seurat objects
OM_TF_LAMs <- subset(x = Om_TFs, idents = c('LAMs'))
OM_TF_PVM <- subset(x = Om_TFs, idents = c('PVM', 'PVM2'))
OM_TF_Bcells <- subset(x = Om_TFs, idents = c('B', 'B1'))
OM_TF_CD4 <- subset(x = Om_TFs, idents = c('CD4+ T'))
OM_TF_CD4NA <- subset(x = Om_TFs, idents = c('NA CD4+ T'))
OM_TF_CD8 <- subset(x = Om_TFs, idents = c('CD8+ T'))
OM_TF_DCs <- subset(x = Om_TFs, idents = c('cDC2A', 'cDC2B'))
OM_TF_ILC <- subset(x = Om_TFs, idents = c('ILC-like'))
OM_TF_NKs <- subset(x = Om_TFs, idents = c('mNK', 'NK-like'))
OM_TF_GDT <- subset(x = Om_TFs, idents = c('γδ T'))
OM_TF_Monocytes <- subset(x = Om_TFs, idents = c('Mono'))
OM_TF_THBS1 <- subset(x = Om_TFs, idents = c('Neu'))

SQ_TF_LAMs <- subset(x = SQ_TFs, idents = c('LAMs'))
SQ_TF_Bcells <- subset(x = SQ_TFs, idents = c('B'))
SQ_TF_CD4 <- subset(x = SQ_TFs, idents = c('CD4+ T'))
SQ_TF_CD8 <- subset(x = SQ_TFs, idents = c('CD8+ T'))
SQ_TF_DCs <- subset(x = SQ_TFs, idents = c('cDC1', 'cDC2A', 'cDC2B'))
SQ_TF_Monocytes <- subset(x = SQ_TFs, idents = c('Mono_Neu'))
SQ_TF_NKs <- subset(x = SQ_TFs, idents = c('NK'))
SQ_TF_PVMs <- subset(x = SQ_TFs, idents = c('PVM', 'PVM2'))
SQ_TF_Treg <- subset(x = SQ_TFs, idents = c('Treg'))
SQ_TF_GDT <- subset(x = SQ_TFs, idents = c('γδ T'))

##Find Markers
OM_TF_LAMs_DEGs <- FindMarkers(OM_TF_LAMs, group.by = "health", ident.1 = "OM_MUO", ident.2 = "OM_MHO")
OM_TF_PVM_DEGs <- FindMarkers(OM_TF_PVM, group.by = "health", ident.1 = "OM_MUO", ident.2 = "OM_MHO")
OM_TF_Bcells_DEGs <- FindMarkers(OM_TF_Bcells, group.by = "health", ident.1 = "OM_MUO", ident.2 = "OM_MHO")
OM_TF_CD4_DEGs <- FindMarkers(OM_TF_CD4, group.by = "health", ident.1 = "OM_MUO", ident.2 = "OM_MHO")
OM_TF_CD4NA_DEGs <- FindMarkers(OM_TF_CD4NA, group.by = "health", ident.1 = "OM_MUO", ident.2 = "OM_MHO")
OM_TF_CD8_DEGs <- FindMarkers(OM_TF_CD8, group.by = "health", ident.1 = "OM_MUO", ident.2 = "OM_MHO")
OM_TF_DCs_DEGs <- FindMarkers(OM_TF_DCs, group.by = "health", ident.1 = "OM_MUO", ident.2 = "OM_MHO")
OM_TF_ILC_DEGs <- FindMarkers(OM_TF_ILC, group.by = "health", ident.1 = "OM_MUO", ident.2 = "OM_MHO")
OM_TF_NKs_DEGs <- FindMarkers(OM_TF_NKs, group.by = "health", ident.1 = "OM_MUO", ident.2 = "OM_MHO")
OM_TF_GDT_DEGs <- FindMarkers(OM_TF_GDT, group.by = "health", ident.1 = "OM_MUO", ident.2 = "OM_MHO")
OM_TF_Monocytes_DEGs <- FindMarkers(OM_TF_Monocytes, group.by = "health", ident.1 = "OM_MUO", ident.2 = "OM_MHO")
OM_TF_THBS1_DEGs <- FindMarkers(OM_TF_THBS1, group.by = "health", ident.1 = "OM_MUO", ident.2 = "OM_MHO")

SQ_TF_LAMs_DEGs <- FindMarkers(SQ_TF_LAMs, group.by = "health", ident.1 = "SQ_MUO", ident.2 = "SQ_MHO")
SQ_TF_Bcells_DEGs <- FindMarkers(SQ_TF_Bcells, group.by = "health", ident.1 = "SQ_MUO", ident.2 = "SQ_MHO")
SQ_TF_CD4_DEGs <- FindMarkers(SQ_TF_CD4, group.by = "health", ident.1 = "SQ_MUO", ident.2 = "SQ_MHO")
SQ_TF_CD8_DEGs <- FindMarkers(SQ_TF_CD8, group.by = "health", ident.1 = "SQ_MUO", ident.2 = "SQ_MHO")
SQ_TF_DCs_DEGs <- FindMarkers(SQ_TF_DCs, group.by = "health", ident.1 = "SQ_MUO", ident.2 = "SQ_MHO")
SQ_TF_Monocytes_DEGs <- FindMarkers(SQ_TF_Monocytes, group.by = "health", ident.1 = "SQ_MUO", ident.2 = "SQ_MHO")
SQ_TF_NKs_DEGs <- FindMarkers(SQ_TF_NKs, group.by = "health", ident.1 = "SQ_MUO", ident.2 = "SQ_MHO")
SQ_TF_PVMs_DEGs <- FindMarkers(SQ_TF_PVMs, group.by = "health", ident.1 = "SQ_MUO", ident.2 = "SQ_MHO")
SQ_TF_Treg_DEGs <- FindMarkers(SQ_TF_Treg, group.by = "health", ident.1 = "SQ_MUO", ident.2 = "SQ_MHO")
SQ_TF_GDT_DEGs <- FindMarkers(SQ_TF_GDT, group.by = "health", ident.1 = "SQ_MUO", ident.2 = "SQ_MHO")

write.xlsx2(OM_TF_LAMs_DEGs, 'OM_TF_LAMs_DEGs.xlsx', sheetName = "Sheet1", col.names = TRUE, row.names = TRUE, append = FALSE)
write.xlsx2(OM_TF_PVM_DEGs, 'OM_TF_PVM_DEGs.xlsx', sheetName = "Sheet1", col.names = TRUE, row.names = TRUE, append = FALSE)
write.xlsx2(OM_TF_Bcells_DEGs, 'OM_TF_Bcells_DEGs.xlsx', sheetName = "Sheet1", col.names = TRUE, row.names = TRUE, append = FALSE)
write.xlsx2(OM_TF_CD4_DEGs, 'OM_TF_CD4_DEGs.xlsx', sheetName = "Sheet1", col.names = TRUE, row.names = TRUE, append = FALSE)
write.xlsx2(OM_TF_CD4NA_DEGs, 'OM_TF_CD4NA_DEGs.xlsx', sheetName = "Sheet1", col.names = TRUE, row.names = TRUE, append = FALSE)
write.xlsx2(OM_TF_CD8_DEGs, 'OM_TF_CD8_DEGs.xlsx', sheetName = "Sheet1", col.names = TRUE, row.names = TRUE, append = FALSE)
write.xlsx2(OM_TF_DCs_DEGs, 'OM_TF_DCs_DEGs.xlsx', sheetName = "Sheet1", col.names = TRUE, row.names = TRUE, append = FALSE)
write.xlsx2(OM_TF_ILC_DEGs, 'OM_TF_ILC_DEGs.xlsx', sheetName = "Sheet1", col.names = TRUE, row.names = TRUE, append = FALSE)
write.xlsx2(OM_TF_NKs_DEGs, 'OM_TF_NKs_DEGs.xlsx', sheetName = "Sheet1", col.names = TRUE, row.names = TRUE, append = FALSE)
write.xlsx2(OM_TF_GDT_DEGs, 'OM_TF_GDT_DEGs.xlsx', sheetName = "Sheet1", col.names = TRUE, row.names = TRUE, append = FALSE)
write.xlsx2(OM_TF_Monocytes_DEGs, 'OM_TF_Monocytes_DEGs.xlsx', sheetName = "Sheet1", col.names = TRUE, row.names = TRUE, append = FALSE)
write.xlsx2(OM_TF_THBS1_DEGs, 'OM_TF_THBS1_DEGs.xlsx', sheetName = "Sheet1", col.names = TRUE, row.names = TRUE, append = FALSE)
write.xlsx2(SQ_TF_LAMs_DEGs, 'SQ_TF_LAMs_DEGs.xlsx', sheetName = "Sheet1", col.names = TRUE, row.names = TRUE, append = FALSE)
write.xlsx2(SQ_TF_Bcells_DEGs, 'SQ_TF_Bcells_DEGs.xlsx', sheetName = "Sheet1", col.names = TRUE, row.names = TRUE, append = FALSE)
write.xlsx2(SQ_TF_CD4_DEGs, 'SQ_TF_CD4_DEGs.xlsx', sheetName = "Sheet1", col.names = TRUE, row.names = TRUE, append = FALSE)
write.xlsx2(SQ_TF_CD8_DEGs, 'SQ_TF_CD8_DEGs.xlsx', sheetName = "Sheet1", col.names = TRUE, row.names = TRUE, append = FALSE)
write.xlsx2(SQ_TF_DCs_DEGs, 'SQ_TF_DCs_DEGs.xlsx', sheetName = "Sheet1", col.names = TRUE, row.names = TRUE, append = FALSE)
write.xlsx2(SQ_TF_Monocytes_DEGs, 'SQ_TF_Monocytes_DEGs.xlsx', sheetName = "Sheet1", col.names = TRUE, row.names = TRUE, append = FALSE)
write.xlsx2(SQ_TF_NKs_DEGs, 'SQ_TF_NKs_DEGs.xlsx', sheetName = "Sheet1", col.names = TRUE, row.names = TRUE, append = FALSE)
write.xlsx2(SQ_TF_PVMs_DEGs, 'SQ_TF_PVMs_DEGs.xlsx', sheetName = "Sheet1", col.names = TRUE, row.names = TRUE, append = FALSE)
write.xlsx2(SQ_TF_Treg_DEGs, 'SQ_TF_Treg_DEGs.xlsx', sheetName = "Sheet1", col.names = TRUE, row.names = TRUE, append = FALSE)
write.xlsx2(SQ_TF_GDT_DEGs, 'SQ_TF_GDT_DEGs.xlsx', sheetName = "Sheet1", col.names = TRUE, row.names = TRUE, append = FALSE)

